name: Build & Release

env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

on:
  push:
    branches:
      - master

defaults:
  run:
    shell: bash

jobs:
  linux_x64: # <-- Primo job: crea la release
    runs-on: ubuntu-latest
    env:
      ELECTRON_PUBLISH_MODE: always

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Install Node.js and NPM
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Build
        run: npm run install-all

      - name: Release
        if: contains(github.ref, 'master')
        run: npm run electron:dist:linux:x64 -- --publish $ELECTRON_PUBLISH_MODE

  linux_arm64:
    runs-on: ubuntu-latest
    env:
      ELECTRON_PUBLISH_MODE: onTag

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Install Node.js and NPM
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Build
        run: npm run install-all

      - name: Release
        if: contains(github.ref, 'master')
        run: npm run electron:dist:linux:arm64 -- --publish $ELECTRON_PUBLISH_MODE

  linux_arm:
    runs-on: ubuntu-latest
    env:
      ELECTRON_PUBLISH_MODE: onTag

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Install Node.js and NPM
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Build
        run: npm run install-all

      - name: Release
        if: contains(github.ref, 'master')
        run: npm run electron:dist:linux:arm -- --publish $ELECTRON_PUBLISH_MODE

  dmg:
    runs-on: macos-latest
    env:
      ELECTRON_PUBLISH_MODE: onTag

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Install Node.js and NPM
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Build
        run: npm run install-all

      - name: Release
        if: contains(github.ref, 'master')
        run: npm run electron:dist:mac:x64 -- --publish $ELECTRON_PUBLISH_MODE

  exe:
    runs-on: windows-latest
    env:
      ELECTRON_PUBLISH_MODE: onTag

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Install Node.js and NPM
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Build
        run: npm run install-all

      - name: Release
        if: contains(github.ref, 'master')
        run: npm run electron:dist:win -- --publish $ELECTRON_PUBLISH_MODE